### ISSUE TITLE
GOAWAY session_timed_out

### ISSUE THREAD

**Issue by asgoel** [codedge-llc/pigeon#81] opened 2017-08-01 20:30 UTC
When using the FCM workers, I see a decent number of the `GOT GOAWAY, NO_ERROR` logs (which it seems like the worker code is aware of). Just wondering what the cause of this is and if there's a way I can mitigate it?

**Comment by hpopp** [comment] 2017-08-01 20:37
In the process of fixing on the `connection-fix` branch. FCM likes to close connections after a few minutes or so, which creates an infinite loop of reconnects (and eventually maxes out CPU).

New intended behavior:
FCM workers will gracefully drop the connection on close and only attempt to connect when there are new pushes to send. This will wipe the existing queue and reset stream IDs, but I think these disconnects are happening due to inactivity, so there shouldn't be pending pushes anyway.

@cstar

**Comment by asgoel** [comment] 2017-08-01 20:58
shouldn't we just make the default ping period lower then?

**Comment by hpopp** [comment] 2017-08-01 21:13
Tried variations down to 5 minutes with no luck. I'm not sure it respects pings, or when it does, `GOAWAY, ENHANCE_YOUR_CALM, too_many_pings` start showing up in the logs. The connection intervals seem to get shorter with every subsequent reconnect, and right about 45 minutes after the initial connection it's closing and reconnecting so fast it overloads everything.

**Comment by asgoel** [comment] 2017-08-01 21:16
Interesting... Dumb question, but I can't find any official documentation on whether FCM supports HTTP/2. Is this just an enhancement you've tried to make, and thus why we are running into so many problems?

**Comment by hpopp** [comment] 2017-08-01 21:25
@cstar wrote the initial implementation. The API works fine except for the reconnect issue, which I'm guessing is due to FCM servers not wanting to persist socket connections until the API is public.

I didn't discover it until I started rolling out onto some staging servers this morning. I should have the patch up pretty soon.

**Closed** 2017-08-01 21:56 UTC

**Comment by 0x6e6562** [comment] 2017-10-13 12:38
@hpopp I'm seeing this sporadically using pigeon 1.1.0 (c0d18bf) and kabadra 0.3.2 (d7afbcfa):

```
[error] Got GOAWAY, NO_ERROR, Last Stream: 0, Rest: session_timed_out
```

With various different stream ids.

Should I be looking into the details of this, or is the session time out just business as usual?

**Comment by hpopp** [comment] 2017-10-13 15:00
FCM closes the connection after a minute or two. No big deal, it just reopens the next time a push is sent.

I should probably have Kadabra disable logging by default.

**Comment by 0x6e6562** [comment] 2017-10-15 20:42
Thanks for the heads up - there doesn't appear to be any material impact on message delivery in any case, so we can just treat this as an ignorable log message.
