### ISSUE TITLE
can channels can be used for push notification 

### ISSUE THREAD

**Issue by siddhant3030** [codedge-llc/pigeon#177] opened 2020-06-29 05:11 UTC
### Environment

* {:pigeon, "~> 1.5.1"},
* {:kadabra, "~> 0.4.4"}
* Erlang version: Erlang/OTP 22 [erts-10.7.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]
* OS: macOS (Catalina) 

hi,

I want to know if I'm using a chat application can I use channels to connect with pigeon and try to receive a notification by subscribing to a particular topic?

For Example

I have created a room with the name max. Whoever joins that room will receive a notification on their app that someone has joined.

I'm not sure if that possible can someone give some pointers on this

**Comment by hpopp** [comment] 2020-06-29 19:28
I'm generally asleep when you're raising and closing these issues. Did you manage to get it worked out?

**Comment by siddhant3030** [comment] 2020-06-29 23:52
oh. I thought I have asked the wrong question. So I have a plan like this creating a gen server and manage the state of the user. Let me know if this can be possible or you can guide me in any other direction.

**Comment by mojidabckuu** [comment] 2020-07-01 15:26
@siddhant3030 the issue is out of library's scope I guess. I believe that it would be more suitable to put this kind of question at elixir forum to get the guidance. 
In general you could track connected users and send a push to **not** connected using `pigeon` and send an event to connected though the socket.

**Closed** 2020-07-13 12:15 UTC
